export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const FB_LOGIN_REQUEST = "FB_LOGIN_REQUEST"
export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"


export const LOGOUT_REQUEST = "LOGOUT_REQUEST"