// export const POPULAR_CATEGORIES_REQUEST='POPULAR_CATEGORIES_REQUEST'
// export const POPULAR_CATEGORIES_SUCCESS='POPULAR_CATEGORIES_SUCCESS'
// export const POPULAR_CATEGORIES_FAILURE='POPULAR_CATEGORIES_FAILURE'

// export const RECENTLY_VIEWED_REQUEST='RECENTLY_VIEWED_REQUEST'
// export const RECENTLY_VIEWED_SUCCESS='RECENTLY_VIEWED_SUCCESS'
// export const RECENTLY_VIEWED_FAILURE='RECENTLY_VIEWED_FAILURE'

// export const RECENTLY_BOUGHT_REQUEST='RECENTLY_BOUGHT_REQUEST'
// export const RECENTLY_BOUGHT_SUCCESS='RECENTLY_BOUGHT_SUCCESS'
// export const RECENTLY_BOUGHT_FAILURE='RECENTLY_BOUGHT_FAILURE'

// export const RECOMMENDED_ROOTS_REQUEST='RECOMMENDED_ROOTS_REQUEST'
// export const RECOMMENDED_ROOTS_SUCCESS='RECOMMENDED_ROOTS_SUCCESS'
// export const RECOMMENDED_ROOTS_FAILURE='RECOMMENDED_ROOTS_FAILURE'

// export const LATEST_ROOTS_REQUEST='LATEST_ROOTS_REQUEST'
// export const LATEST_ROOTS_SUCCESS='LATEST_ROOTS_SUCCESS'
// export const LATEST_ROOTS_FAILURE='LATEST_ROOTS_FAILURE'

// export const TOP_ROOTS_REQUEST='TOP_ROOTS_REQUEST'
// export const TOP_ROOTS_SUCCESS='TOP_ROOTS_SUCCESS'
// export const TOP_REQUEST_FAILURE='TOP_REQUEST_FAILURE'


// export const ALL_ROOTS_REQUEST='ALL_ROOTS_REQUEST'
// export const ALL_ROOTS_SUCCESS='ALL_ROOTS_SUCCESS'
// export const ALL_REQUEST_FAILURE='ALL_REQUEST_FAILURE'

export const ROOTS_REQUEST = 'ROOTS_REQUEST'
export const ROOTS_SUCCESS = 'ROOTS_SUCCESS'
export const ROOTS_FAILURE = 'REQUEST_FAILURE'

export const LATEST_ROOTS_REQUEST='LATEST_ROOTS_REQUEST'
export const LATEST_ROOTS_SUCCESS='LATEST_ROOTS_SUCCESS'
export const LATEST_ROOTS_FAILURE='LATEST_ROOTS_FAILURE'

export const CATEGORY_PICKER_REQUEST = "CATEGORY_PICKER_REQUEST"
export const CATEGORY_PICKER_SUCCESS = "CATEGORY_PICKER_SUCCESS"
export const CATEGORY_PICKER_FAILURE = "CATEGORY_PICKER_FAILURE"

// export const REGEX_PICKER_REQUEST = "REGEX_PICKER_REQUEST"
// export const REGEX_PICKER_SUCCESS = "REGEX_PICKER_SUCCESS"
// export const REGEX_PICKER_FAILURE = "REGEX_PICKER_FAILURE"

