import { notifications } from "react-native-firebase"
const server = 'https://www.talentsroot.com/api_v1/'
// const server = 'https://talentsroot.tribital.ml/api_v1/'
// const server ='https://talentsroot.lembits.in/api_v1/'

const config = {
    register: server + 'register',
    login: server + 'login',
    logout: server + 'logout',
    registerFCM: server + 'register-device',
    facebookLogin: server + 'facebook-login',
    facebookRegister: server + 'facebook-register',
    googleLogin: server + 'google-login',
    googleRegister: server + 'google-register',
    home: server + 'home/dashboard',
    profile: server + 'user/profile',
    userProfile: server + 'root/user-profile',
    postRoot: server + 'root/add',
    rootDetails: server + 'root/details',
    reviewDetail: server + 'root/reviews',
    otherRootsDetail: server + 'root/other-roots',
    userRootsDetail: server + 'user/roots',
    editProfile: server + 'user/profile-edit',
    mysales: server + 'order/sales-list',
    userBalance: server + 'user/get-balance',
    myReviews: server + 'reviews/received',
    userReviews: server + 'reviews/user-reviews',
    awardedReviews: server + 'reviews/awarded',
    pendigReviews: server + 'reviews/pending',
    categories: server + 'home/categories',
    subcategories: server + 'home/subcategories?category_id=',
    myShopping: server + 'order/shopping-list',
    vacation: server + 'user/vacation-mode',
    myRequests: server + 'requests/my-requests',
    editRequest: server + 'requests/new',
    buyersRequests: server + 'requests/buyer-requests',
    rootList: server + 'root/rootslistbycategory',
    cancelOrder: server + 'order/cancel',
    cancelActionOrder: server + 'order/cancel-action',
    addCustom: server + 'order/add-custom-extra',
    extendOrder: server + 'order/extend-delivery-time',
    extendDeliverTime: server + 'order/extend-delivery-time',
    cancelExtendDelivery: server + 'order/extend-delivery-action',
    cancelCustomExtra: server + 'order/custom-extra-action',
    addCustomExtra: server + 'order/add-custom-extra',
    deliverOrder: server + 'order/deliver',
    acceptOrder: server + 'order/accept',
    submitRating : server + 'order/rating',
    transaction: server + 'payments/transactions',
    payments_withdrawl: server + 'payments/withdrawals',
    payment_clearance: server + 'payments/clearance',
    withdraw_money: server + 'payments/withdraw-request',
    notifications: server + 'notification/list',
    root_notification: server + 'notification/root',
    notificationRead: server + 'notification/action',
    forgetPassword: server + 'user/forgot-password',
    advancedSearch: server + 'home/search-list',
    send_offer: server + 'requests/send-offer',
    request: server + 'requests/new',
    country: server + 'home/country',
    language: server + 'home/language',
    timezone: server + 'home/timezone',
    checkout: server + 'order/checkout',
    apply_coupon: server + 'order/coupon',
    change_password: server + 'user/change-password',
    chat_list: server + 'chat/chat-list',
    chat_eventread: server + 'chat/event-read',
    chat_eventtyping: server + 'chat/event-typing',
    conversation: server + 'chat/conversation',
    conversation_list: server + 'chat/conversation-list',
    send_message: server + 'chat/send',
    favourite_chat: server + 'chat/favourite',
    upload_file: server + 'chat/uploadfile',
    block_user: server + 'chat/block',
    get_roots: server + 'root/list',
    custom_offer: server + 'chat/custom-offer',
    success_order: server + 'order/success',
    myFavorites: server + 'root/favorites',
    removeFavorites: server + 'root/remove-favorites',
    addFavorites: server + 'root/add-favorites',
    orderHistory: server + 'order/history',
    deleteFileInRequest: server + 'requests/delete-file',
    customOfferReject: server + 'chat/custom-offer-action',
    getRegex: server + 'chat/word-filter',
    reportThis: server + 'root/report',
    rootAction: server + 'root/action',
    deleteFileInRequest: server + 'requests/delete-file',
    getRegex: server + 'chat/word-filter',
    reportThis: server + 'root/report',
    rootAction: server + 'root/action',
    checkFavorite: server + 'root/check-favorites',
}

export default config;


