export const ROOT_TITLE_SAVE = "ROOT_TITLE_SAVE"
export const ROOT_PRICING_SAVE = "ROOT_PRICING_SAVE"
export const ROOT_DETAILS_SAVE = "ROOT_DETAILS_SAVE"
export const CLEAR_ROOT = "CLEAR_ROOT"
export const SAVE_ROOT = "SAVE_ROOT"



