import * as types from '../actions';

const initialState = {
  rootTitle: '',
  category: '',
  subCategory: '',
  isPriceFlexible : 0,
  price : '',
  deliveryDays : '',
  fastDeliveryPrice  : '',
  fastDeliveryDays : '',
  revisionPrice : '',
  revisionDays : '',
  extra1Description : '',
  extra1Price : '',
  extra1Days : '',
  extra2Description : '',
  extra2Price : '',
  extra2Days : '',
  extra3Description : '',
  extra3Price : '',
  extra3Days : '',
  basicName : '',
  standardName : '',
  premiumName : '',
  basicDescription : '',
  standardDescription : '',
  premiumDescription : '',
  basicMaxDays : '',
  standardMaxDays : '',
  premiumMaxDays : '',
  basicPrice : '',
  standardPrice : '',
  premiumPrice : '',
  basicRevision : '',
  standardRevision : '',
  premiumRevision : '',
  description: '',
  instruction:'',
  tags:'',
  image:'',
  videos:'',
  rootId:'',
  rootType:'',//0=post 1=draft
  isExtraFastDelivery:false,
  isRevision: false,
  isExtra1: false,
  isExtra2: false,
  isExtra3: false,
};

export default function addRoot(state = initialState, action) {
  switch (action.type) {
    case types.ROOT_TITLE_SAVE:
      return {
        ...state,
        rootTitle: action.payload.rootTitle,
        category: action.payload.category,
        subCategory: action.payload.subCategory,
      };
    case types.ROOT_PRICING_SAVE:
      return {
        ...state,
        isPriceFlexible:  action.payload.isPriceFlexible ? 1: 0,
        price: action.payload.price,
        deliveryDays: action.payload.deliveryDays,
        fastDeliveryPrice : action.payload.fastDeliveryPrice ,
        fastDeliveryDays: action.payload.fastDeliveryDays,
        revisionPrice:  action.payload.revisionPrice,
        revisionDays: action.payload.revisionDays,
        extra1Description: action.payload.extra1Description,
        extra1Price: action.payload.extra1Price,
        extra1Days: action.payload.extra1Days,
        extra2Description: action.payload.extra2Description,
        extra2Price: action.payload.extra2Price,
        extra2Days: action.payload.extra2Days,
        extra3Description: action.payload.extra3Description,
        extra3Price: action.payload.extra3Price,
        extra3Days: action.payload.extra3Days,
        basicName: action.payload.basicName,
        standardName: action.payload.standardName,
        premiumName: action.payload.premiumName,
        basicDescription: action.payload.basicDescription,
        standardDescription: action.payload.standardDescription,
        premiumDescription: action.payload.premiumDescription,
        basicMaxDays: action.payload.basicMaxDays,
        standardMaxDays: action.payload.standardMaxDays,
        premiumMaxDays: action.payload.premiumMaxDays,
        basicPrice: action.payload.basicPrice,
        standardPrice: action.payload.standardPrice,
        premiumPrice: action.payload.premiumPrice,
        basicRevision:action.payload.basicRevision,
        standardRevision: action.payload.standardRevision,
        premiumRevision: action.payload.premiumRevision,
        isExtraFastDelivery: action.payload.isExtraFastDelivery,
        isRevision: action.payload.isRevision,
        isExtra1: action.payload.isExtra1,
        isExtra2: action.payload.isExtra2,
        isExtra3: action.payload.isExtra3,
      };
    case types.ROOT_DETAILS_SAVE:
      return {
        ...state,
        description:action.payload.description,
        tags:action.payload.tags,
        instruction:action.payload.instruction,
        image:action.payload.image,
        videos:action.payload.videos
      };
    case types.CLEAR_ROOT:
      return {
        ...state,
        rootTitle: '',
        category: '',
        subCategory: '',
        isPriceFlexible: '',
        price: '',
        deliveryDays: '',
        fastDeliveryPrice : '',
        fastDeliveryDays: '',
        revisionPrice:  '',
        revisionDays: '',
        extra1Description: '',
        extra1Price: '',
        extra1Days: '',
        extra2Description:'',
        extra2Price: '',
        extra2Days:'',
        extra3Description: '',
        extra3Price: '',
        extra3Days:'',
        basicName:'',
        standardName:'',
        premiumName: '',
        basicDescription:'',
        standardDescription: '',
        premiumDescription:'',
        basicMaxDays: '',
        standardMaxDays:'',
        premiumMaxDays:'',
        basicPrice:'',
        standardPrice: '',
        premiumPrice: '',
        basicRevision:'',
        standardRevision: '',
        premiumRevision:'',
        isExtraFastDelivery: '',
        isRevision:'',
        isExtra1:'',
        isExtra2: '',
        isExtra3: '',
        description:'',
        tags:'',
        instruction:'',
        image:'',
        videos:'',
        rootId:''
      };  
    case types.SAVE_ROOT:
      console.log('data in reducer',action.payload)
      let flexiblePrice = JSON.parse(action.payload.r_flexible_price);
      if (flexiblePrice){
      }
      return {
        ...state,
        rootTitle: action.payload.r_title,
        category: action.payload.r_category_id,
        subCategory: action.payload.r_subcategory_ids,
        isPriceFlexible: action.payload.r_price_status,
        price: action.payload.r_fiixed_price.price,
        deliveryDays: action.payload.r_fiixed_price.max_days,
        fastDeliveryPrice : action.payload.r_extra.fast_delivery.price,
        fastDeliveryDays: action.payload.r_extra.fast_delivery.max_days,
        revisionPrice:  action.payload.r_extra.revision.price,
        revisionDays: action.payload.r_extra.revision.max_days,
        extra1Description: action.payload.r_extra.extra1.description,
        extra1Price:  action.payload.r_extra.extra1.price,
        extra1Days:  action.payload.r_extra.extra1.max_days,
        extra2Description: action.payload.r_extra.extra2.description,
        extra2Price:  action.payload.r_extra.extra2.price,
        extra2Days: action.payload.r_extra.extra2.max_days,
        extra3Description:  action.payload.r_extra.extra3.description,
        extra3Price:  action.payload.r_extra.extra3.price,
        extra3Days: action.payload.r_extra.extra3.max_days,
        basicName: flexiblePrice.basic != undefined?flexiblePrice.basic.name:'',
        standardName:flexiblePrice.standard != undefined?flexiblePrice.standard.name:'',
        premiumName: flexiblePrice.premium != undefined?flexiblePrice.premium.name:'',
        basicDescription:flexiblePrice.basic != undefined?flexiblePrice.basic.description:'',
        standardDescription: flexiblePrice.standard != undefined?flexiblePrice.standard.description:'',
        premiumDescription:flexiblePrice.premium != undefined?flexiblePrice.premium.description:'',
        basicMaxDays: flexiblePrice.basic != undefined?flexiblePrice.basic.max_days:'',
        standardMaxDays:flexiblePrice.standard != undefined?flexiblePrice.standard.max_days:'',
        premiumMaxDays:flexiblePrice.premium != undefined?flexiblePrice.premium.max_days:'',
        basicPrice:flexiblePrice.basic != undefined?flexiblePrice.basic.price:'',
        standardPrice: flexiblePrice.standard != undefined?flexiblePrice.standard.price:'',
        premiumPrice: flexiblePrice.premium != undefined?flexiblePrice.premium.price:'',
        basicRevision:flexiblePrice.basic != undefined?flexiblePrice.basic.revision:'',
        standardRevision: flexiblePrice.standard != undefined?flexiblePrice.standard.revision:'',
        premiumRevision:flexiblePrice.premium != undefined?flexiblePrice.premium.revision:'',
        isExtraFastDelivery: action.payload.r_extra.fast_delivery.status === 'checked' ? true : false,
        isRevision:action.payload.r_extra.revision.status === 'checked' ? true : false,
        isExtra1: action.payload.r_extra.extra1.price ? true : false,
        isExtra2: action.payload.r_extra.extra2.price ? true : false,
        isExtra3: action.payload.r_extra.extra3.price ? true : false,
        description:action.payload.r_desc,
        tags:action.payload.r_tags,
        instruction:action.payload.r_instruction_to_buyer,
        image:action.payload.c_image,
        videos:action.payload.r_video_link,
        rootId:action.payload.r_id
      };  
    default:
      return state;
  }
}



/*





  'r_title': '',
  'r_category_id':'',
  'r_subcategory_ids':'',
  'r_price_status':0,//0 = Fixed,1=Flexibel
  'r_minimum_price': 5,
  'r_fiixed_price[price]': '',
  'r_fiixed_price[max_days]': '',

  'r_extra[fast_delivery][price]':'',
  'r_extra[fast_delivery][max_days]':'',
  'r_extra[revision][price]':'',
  'r_extra[revision][max_days]':'',
  'r_extra[extra1][description]':'',
  'r_extra[extra1][price]':'',
  'r_extra[extra1][max_days]':'',
  'r_extra[extra2][description]':'',
  'r_extra[extra2][price]':'',
  'r_extra[extra2][max_days]':'',
  'r_extra[extra3][description]':'',
  'r_extra[extra3][price]':'',
  'r_extra[extra3][max_days]':'',

  'r_flexible_price[basic][name]':'',
  'r_flexible_price[standard][name]':'',
  'r_flexible_price[premium][name]':'',
  'r_flexible_price[basic][description]':'',
  'r_flexible_price[standard][description]':'',
  'r_flexible_price[premium][description]':'',
  'r_flexible_price[basic][max_days]':'',
  'r_flexible_price[standard][max_days]':'',
  'r_flexible_price[premium][max_days]':'',
  'r_flexible_price[basic][price]':'',
  'r_flexible_price[standard][price]':'',
  'r_flexible_price[premium][price]':'',
  'r_flexible_price[basic][revision]':'',
  'r_flexible_price[standard][revision]':'',
  'r_flexible_price[premium][revision]':'',
  
  'r_desc': '',
  'r_root_file[]': '',
  'r_id':'',
  'r_type':'',//0=post 1=draft
  'r_tags':'',
  'r_instruction_to_buyer':''
*/